
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cr.ac.ucr.ci1322;

/** CUP generated interface containing symbol constants. */
public interface Terminal {
  /* terminals */
  public static final int T_RIGHT_PARENTHESIS = 9;
  public static final int T_INTEGER = 2;
  public static final int T_IDENTIFIER = 3;
  public static final int T_NEWLINES = 7;
  public static final int T_EQUALS = 6;
  public static final int EOF = 0;
  public static final int T_PRINT = 5;
  public static final int T_READ = 4;
  public static final int T_LEFT_PARENTHESIS = 8;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_INTEGER",
  "T_IDENTIFIER",
  "T_READ",
  "T_PRINT",
  "T_EQUALS",
  "T_NEWLINES",
  "T_LEFT_PARENTHESIS",
  "T_RIGHT_PARENTHESIS"
  };
}

